const mongoose = require('mongoose');

const stepSchema = new mongoose.Schema({
  order: { type: Number, required: true },
  description: { type: String, required: true },
  expectedResult: { type: String, default: '' },
  actualResult: { type: String, default: '' },
  status: { type: String, enum: ['pending', 'pass', 'fail', 'blocked', 'not_tested'], default: 'pending' },
  evidence: { type: String, default: '' },
  historical: { type: Boolean, default: false },
}, { _id: true });

const executionSchema = new mongoose.Schema({
  executionNumber: { type: Number, required: true },
  status: { type: String, enum: ['passed', 'failed', 'retest_passed', 'retest_failed'], required: true },
  executedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  executedAt: { type: Date, default: Date.now },
  steps: [{
    order: Number,
    description: String,
    expectedResult: String,
    actualResult: String,
    status: { type: String, enum: ['pending', 'pass', 'fail', 'blocked', 'not_tested'] },
    evidence: String,
  }],
  failureReason: { type: String, default: '' },
  screenshot: { type: String, default: '' },
  linkedBug: { type: mongoose.Schema.Types.ObjectId, ref: 'Bug' },
}, { _id: true });

const testCaseSchema = new mongoose.Schema({
  testCaseId: { type: String },
  title: { type: String, required: true, trim: true },
  description: { type: String, default: '' },
  feature: { type: String, default: '' },
  type: {
    type: String,
    enum: ['integration', 'unit', 'e2e', 'security', 'performance', 'manual'],
    default: 'manual',
  },
  priority: {
    type: String,
    enum: ['low', 'medium', 'high', 'urgent', 'critical'],
    default: 'medium',
  },
  status: {
    type: String,
    enum: ['draft', 'ready', 'in_progress', 'passed', 'failed', 'blocked', 'skipped', 'retesting', 'auto-draft'],
    default: 'draft',
  },
  precondition: { type: String, default: '' },
  steps: [stepSchema],
  project: { type: mongoose.Schema.Types.ObjectId, ref: 'Project', required: true },
  sprint: { type: mongoose.Schema.Types.ObjectId, ref: 'Sprint' },
  assignee: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  linkedTask: { type: mongoose.Schema.Types.ObjectId, ref: 'Task' },
  linkedBug: { type: mongoose.Schema.Types.ObjectId, ref: 'Bug' },
  createdBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  executedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
  executedAt: { type: Date },
  failureReason: { type: String, default: '' },
  attachments: [{
    filename: String,
    originalName: String,
    path: String,
    mimeType: String,
    uploadedBy: { type: mongoose.Schema.Types.ObjectId, ref: 'User' },
    uploadedAt: { type: Date, default: Date.now },
  }],
  tags: [{ type: String }],
  isActive: { type: Boolean, default: true },
  interestMatchScore: { type: Number, default: 100, min: 0, max: 100 },
  interestMatchStatus: { type: String, enum: ['high', 'low', 'flagged'], default: 'high' },
  flaggedForDeletion: { type: Boolean, default: false },
  flaggedAt: { type: Date },
  autoDeleteAt: { type: Date },
  autoGenerated: { type: Boolean, default: false },
  lastRunAt: { type: Date },
  executionHistory: [executionSchema],
  executionCount: { type: Number, default: 0 },
  bugCount: { type: Number, default: 0 },
  retestRequired: { type: Boolean, default: false },
}, { timestamps: true });

testCaseSchema.pre('save', async function (next) {
  if (!this.testCaseId) {
    const TestCase = mongoose.model('TestCase');
    const last = await TestCase.findOne({ project: this.project })
      .sort({ testCaseId: -1 })
      .select('testCaseId')
      .lean();
    let num = 1;
    if (last && last.testCaseId) {
      const parsed = parseInt(last.testCaseId.replace('TC-', ''), 10);
      if (!isNaN(parsed)) num = parsed + 1;
    }
    this.testCaseId = `TC-${String(num).padStart(3, '0')}`;
  }
  next();
});

testCaseSchema.index({ project: 1, status: 1 });
testCaseSchema.index({ project: 1, testCaseId: 1 });

module.exports = mongoose.model('TestCase', testCaseSchema);