const { Router } = require('express');
const { getBugs, getBugById, createBug, resolveBug, reopenBug, triggerRetest, updateBug, getBugStats } = require('../controllers/bugController');
const { auth, authorize } = require('../middleware/auth');
const router = Router();
router.use(auth);
router.get('/', getBugs);
router.get('/stats/:projectId?', getBugStats);
router.post('/', authorize('admin', 'project_manager', 'team_lead', 'qa_tester'), createBug);
router.get('/:id', getBugById);
router.patch('/:id', authorize('admin', 'project_manager', 'team_lead', 'qa_tester'), updateBug);
router.post('/:id/resolve', authorize('admin', 'project_manager', 'team_lead'), resolveBug);
router.post('/:id/reopen', authorize('admin', 'project_manager', 'team_lead', 'qa_tester'), reopenBug);
router.post('/:id/retest', authorize('admin', 'project_manager', 'team_lead', 'qa_tester'), triggerRetest);
module.exports = router;
