const { Router } = require('express');
const { getUsers, getUserById, createUser, updateUser, deleteUser, moveUserDepartment, getUserActivity, getUserProfile, getCapacity } = require('../controllers/userController');
const { auth, authorize } = require('../middleware/auth');
const { user } = require('../middleware/validate');
const router = Router();
router.use(auth);
router.get('/', getUsers);
router.get('/capacity', getCapacity);
router.get('/profile', (req, res, next) => { req.params.id = req.user._id; next(); }, getUserProfile);
router.get('/:id/activity', getUserActivity);
router.get('/:id/profile', getUserProfile);
router.get('/:id', getUserById);
router.post('/', authorize('admin'), user.create, createUser);
router.patch('/:id', authorize('admin', 'project_manager', 'team_lead', 'manager'), user.update, updateUser);
router.patch('/:id/department', authorize('admin'), moveUserDepartment);
router.delete('/:id', authorize('admin'), deleteUser);
module.exports = router;
