import { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import { useAuth } from '../context/AuthContext';
import { testCases, interests, bugs, projects } from '../services/api';
import TestRunner from '../components/TestRunner';
import Dropdown from '../components/Dropdown';

const ALL_STATUSES = ['draft', 'auto-draft', 'ready', 'in_progress', 'passed', 'failed', 'blocked', 'skipped', 'retesting'];

const TABS = [
  { key: 'all', label: 'All Tests' },
  { key: 'auto', label: 'Auto-Generated' },
  { key: 'flagged', label: 'Flagged' },
  { key: 'bugs', label: 'Bugs' },
  { key: 'config', label: 'Interest Config' },
];

const STATUS_CLASS = {
  draft: 'tb-todo',
  'auto-draft': 'tb-todo',
  ready: 'tb-ip',
  in_progress: 'tb-ip',
  retesting: 'tb-rv',
  passed: 'tb-dn',
  failed: 'tb-dl',
  blocked: 'tb-rv',
  skipped: 'tb-todo',
};

const SEVERITY_CLS = {
  critical: 'tp-u',
  high: 'tp-h',
  medium: 'tp-m',
  low: 'tp-l',
};

const BUG_STATUS_CLS = {
  open: 'tb-dl',
  in_progress: 'tb-ip',
  fixed: 'tb-rv',
  closed: 'tb-dn',
  reopened: 'tb-dl',
};

const TEST_COLUMNS = [
  { key: 'draft', label: 'Draft', statuses: ['draft', 'auto-draft'], dot: '#9ca3af', border: 'border-t-gray-400', bg: 'bg-gray-50' },
  { key: 'ready', label: 'Ready', statuses: ['ready'], dot: '#3b82f6', border: 'border-t-blue-500', bg: 'bg-blue-50' },
  { key: 'in_progress', label: 'In Progress', statuses: ['in_progress', 'retesting'], dot: '#f59e0b', border: 'border-t-amber-500', bg: 'bg-amber-50' },
  { key: 'passed', label: 'Passed', statuses: ['passed'], dot: '#22c55e', border: 'border-t-emerald-500', bg: 'bg-emerald-50' },
  { key: 'issues', label: 'Issues', statuses: ['failed', 'blocked', 'skipped'], dot: '#ef4444', border: 'border-t-red-500', bg: 'bg-red-50' },
];

export default function TestCaseDashboard() {
  const { projectId: urlProjectId } = useParams();
  const { user, socket } = useAuth();
  const navigate = useNavigate();
  const isManager = ['admin', 'project_manager', 'team_lead', 'qa_tester'].includes(user?.role);
  const isAdmin = user?.role === 'admin';
  const canEdit = ['admin', 'project_manager', 'team_lead', 'manager', 'qa_tester'].includes(user?.role);

  const [activeTab, setActiveTab] = useState('all');
  const [projectList, setProjectList] = useState([]);
  const [selectedProject, setSelectedProject] = useState(urlProjectId || '');
  const [loading, setLoading] = useState(false);
  const [testList, setTestList] = useState([]);
  const [autoList, setAutoList] = useState([]);
  const [flaggedList, setFlaggedList] = useState([]);
  const [bugList, setBugList] = useState([]);
  const [interestConfig, setInterestConfig] = useState({ interestTags: [], priorityFeatures: [], ignorePatterns: [], autoDeleteEnabled: true, autoDeleteDays: 7 });
  const [stats, setStats] = useState(null);
  const [bugStats, setBugStats] = useState(null);
  const [testToRun, setTestToRun] = useState(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
  const [confirmDeleteId, setConfirmDeleteId] = useState(null);
  const [editTest, setEditTest] = useState(null);
  const [editStatus, setEditStatus] = useState('');
  const [editAssignee, setEditAssignee] = useState('');
  const [qaMembers, setQaMembers] = useState([]);
  const [showNewForm, setShowNewForm] = useState(false);
  const [newForm, setNewForm] = useState({ title: '', description: '', type: 'manual', priority: 'medium' });
  const [draggedTest, setDraggedTest] = useState(null);

  useEffect(() => {
    projects.getAll().then(res => setProjectList(res.data)).catch(() => {});
  }, []);

  const fetchData = useCallback(async () => {
    if (!selectedProject) return;
    setLoading(true);
    try {
      const params = { project: selectedProject };
      const [testsRes, autoRes, flaggedRes, bugsRes, statsRes, bugStatsRes, interestRes] = await Promise.all([
        testCases.getAll(params).catch(() => ({ data: [] })),
        testCases.getAutoGenerated(selectedProject).catch(() => ({ data: [] })),
        interests.getFlagged(selectedProject).catch(() => ({ data: [] })),
        bugs.getAll({ projectId: selectedProject }).catch(() => ({ data: [] })),
        testCases.getStats(selectedProject).catch(() => null),
        bugs.getStats(selectedProject).catch(() => null),
        interests.getProjectInterests(selectedProject).catch(() => null),
      ]);
      setTestList(testsRes.data);
      setAutoList(autoRes.data);
      setFlaggedList(flaggedRes.data);
      setBugList(bugsRes.data);
      setStats(statsRes?.data);
      setBugStats(bugStatsRes?.data);
      if (interestRes?.data) {
        setInterestConfig({
          interestTags: interestRes.data.interestTags || [],
          priorityFeatures: interestRes.data.priorityFeatures || [],
          ignorePatterns: interestRes.data.ignorePatterns || [],
          autoDeleteEnabled: interestRes.data.autoDeleteEnabled ?? true,
          autoDeleteDays: interestRes.data.autoDeleteDays || 7,
        });
      }
    } catch (e) { toast.error('Failed to load data'); }
    setLoading(false);
  }, [selectedProject]);

  useEffect(() => { fetchData(); }, [fetchData]);

  // Socket: listen for test case events across the project
  useEffect(() => {
    if (!socket || !selectedProject) return;
    socket.emit('join_project', selectedProject);

    const refresh = () => fetchData();

    socket.on('test_case_created', refresh);
    socket.on('test_case_updated', refresh);
    socket.on('test_case_executed', refresh);
    socket.on('test_case_deleted', refresh);
    socket.on('test_cases_bulk_created', refresh);
    socket.on('test_cases_auto_generated', refresh);

    return () => {
      socket.emit('leave_project', selectedProject);
      socket.off('test_case_created', refresh);
      socket.off('test_case_updated', refresh);
      socket.off('test_case_executed', refresh);
      socket.off('test_case_deleted', refresh);
      socket.off('test_cases_bulk_created', refresh);
      socket.off('test_cases_auto_generated', refresh);
    };
  }, [socket, selectedProject]);

  const handleNewTest = async () => {
    if (!newForm.title.trim()) return toast.error('Title is required');
    try {
      await testCases.create({ ...newForm, project: selectedProject });
      toast.success('Test case created');
      setShowNewForm(false);
      setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' });
      fetchData();
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed to create test case');
    }
  };

  const handleGenerateTests = async () => {
    if (!selectedProject) return toast.error('Select a project first');
    try {
      const res = await testCases.autoGenerate({ project: selectedProject });
      toast.success(`Generated ${res.data.length} test cases`);
      fetchData();
    } catch (e) {
      const msg = e.response?.data?.message || 'Generation failed';
      if (msg.includes('No tasks')) toast.error('No tasks found to generate from');
      else toast.error(msg);
    }
  };

  const handleGenerateCompleted = async () => {
    if (!selectedProject) return toast.error('Select a project first');
    try {
      const res = await testCases.generateCompleted({ projectId: selectedProject });
      toast.success(res.data.message);
      fetchData();
    } catch (e) {
      toast.error(e.response?.data?.message || 'Failed');
    }
  };

  const handleRunFilter = async () => {
    if (!selectedProject) return;
    try {
      const res = await interests.runFilter(selectedProject);
      toast.success(`Filter applied: ${res.data.flagged} flagged`);
      fetchData();
    } catch (e) { toast.error('Filter failed'); }
  };

  const handleRestoreFlagged = async (id) => {
    try {
      await interests.restoreFlagged(id);
      toast.success('Test case restored');
      fetchData();
    } catch (e) { toast.error('Restore failed'); }
  };

  const handleRestoreAll = async () => {
    try {
      const res = await interests.restoreAllFlagged();
      toast.success(`Restored ${res.data.count} test cases`);
      fetchData();
    } catch (e) { toast.error('Restore failed'); }
  };

  const handleDeleteAllFlagged = async () => {
    try {
      const res = await interests.deleteAllFlagged();
      toast.success(`Deleted ${res.data.count} test cases`);
      setShowDeleteConfirm(false);
      fetchData();
    } catch (e) { toast.error('Delete failed'); }
  };

  const handleSaveInterestConfig = async () => {
    if (!selectedProject) return;
    try {
      await interests.updateProjectInterests(selectedProject, interestConfig);
      toast.success('Interest config saved');
      fetchData();
    } catch (e) { toast.error('Save failed'); }
  };

  const handleResolveBug = async (bugId) => {
    const notes = prompt('Resolution notes:');
    if (notes === null) return;
    try {
      await bugs.resolve(bugId, { resolutionNotes: notes || 'Resolved' });
      toast.success('Bug resolved');
      fetchData();
    } catch (e) { toast.error('Resolve failed'); }
  };

  const handleReopenBug = async (bugId) => {
    const reason = prompt('Failure reason for retest:');
    if (reason === null) return;
    try {
      await bugs.reopen(bugId, { failureReason: reason || 'Retest failed' });
      toast.success('Bug reopened');
      fetchData();
    } catch (e) { toast.error('Reopen failed'); }
  };

  const handleDeleteTest = async (id) => {
    try {
      await testCases.delete(id);
      toast.success('Test case deleted');
      fetchData();
    } catch (e) { toast.error('Delete failed'); }
  };

  const handleRetestTest = async (id) => {
    try {
      await testCases.retest(id);
      toast.success('Test reset for retesting');
      fetchData();
    } catch (e) { toast.error('Retest failed'); }
  };

  const handleOpenEdit = async (tc) => {
    setEditStatus(tc.status);
    setEditAssignee(tc.assignee?._id || '');
    setEditTest(tc);
    try {
      const res = await projects.getTeam(selectedProject);
      const members = Array.isArray(res.data) ? res.data : res.data?.members || [];
      setQaMembers(members.filter(m => m.projectRole === 'qa_tester' && m.status === 'active'));
    } catch (e) { setQaMembers([]); }
  };

  const handleSaveEdit = async () => {
    if (!editTest) return;
    try {
      const data = {};
      if (editStatus !== editTest.status) data.status = editStatus;
      const newAssigneeId = editAssignee || null;
      const oldAssigneeId = editTest.assignee?._id || null;
      if (newAssigneeId !== oldAssigneeId) data.assignee = newAssigneeId;
      if (Object.keys(data).length === 0) { setEditTest(null); return; }
      await testCases.update(editTest._id, data);
      toast.success('Test case updated');
      setEditTest(null);
      fetchData();
    } catch (e) { toast.error(e.response?.data?.message || 'Update failed'); }
  };

  const handleInlineTestStatus = async (testId, newStatus) => {
    try {
      await testCases.update(testId, { status: newStatus });
      toast.success(`Status set to ${newStatus.replace('_', ' ')}`);
      fetchData();
    } catch (e) { toast.error(e.response?.data?.message || 'Update failed'); }
  };

  const handleTestDrop = async (testId, columnKey) => {
    setDraggedTest(null);
    const col = TEST_COLUMNS.find(c => c.key === columnKey);
    if (!col) return;
    const newStatus = col.statuses[0];
    await handleInlineTestStatus(testId, newStatus);
  };

  if (!projectList.length && !selectedProject) {
    return (
      <div>
        <div style={{fontSize:18,fontWeight:700,color:'#111827',marginBottom:12}}>🧪 Test Case Dashboard</div>
        <div className="card" style={{padding:'40px 20px',textAlign:'center'}}>
          <p style={{color:'#9ca3af',fontSize:12}}>No projects found.</p>
          <p style={{color:'#9ca3af',fontSize:11,marginTop:4}}>Create a project to start managing test cases.</p>
        </div>
      </div>
    );
  }

  return (
    <div>
      <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:12}}>
        <div>
          <div style={{fontSize:18,fontWeight:700,color:'#111827'}}>🧪 Test Case Dashboard</div>
          <div style={{fontSize:11,color:'#9ca3af',marginTop:1}}>{testList.length} test cases</div>
        </div>
        <Dropdown value={selectedProject} onChange={v => setSelectedProject(v)}
          options={[{value:'', label:'Select a project...'}, ...projectList.map(p => ({value:p._id, label:p.name}))]} style={{minWidth:180}} />
      </div>

      {!selectedProject ? (
        <div className="card" style={{padding:'40px 20px',textAlign:'center'}}>
          <p style={{color:'#9ca3af',fontSize:12}}>Select a project to view its test cases.</p>
        </div>
      ) : (
        <>
          {stats && (
            <div className="stats-grid" style={{gridTemplateColumns:'repeat(5,1fr)'}}>
              <div className="stat-pill"><div className="sp-n">{stats.total}</div><div className="sp-l">Total</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{stats.passRate}%</div><div className="sp-l">Pass Rate</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#1d4ed8'}}>{stats.coverage}%</div><div className="sp-l">Coverage</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{stats.passed}</div><div className="sp-l">Passed</div></div>
              <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{stats.failed}</div><div className="sp-l">Failed</div></div>
            </div>
          )}

          {/* Tabs */}
            <div className="card" style={{padding:0,marginBottom:12,overflow:'hidden'}}>
            <div className="tabs" style={{background:'transparent',padding:0}}>
              {TABS.map(tab => (
                <div key={tab.key} onClick={() => setActiveTab(tab.key)}
                  data-voice={`tab-${tab.key}`}
                  className={`tab ${activeTab === tab.key ? 'active' : ''}`}
                  style={{fontSize:11,padding:'8px 12px'}}>
                  {tab.label}
                </div>
              ))}
            </div>
          </div>

          {/* Tab Content */}
          <div className="card" style={{padding:'14px 16px'}}>
            {loading ? (
              <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>Loading...</div>
            ) : activeTab === 'all' ? renderAllTests() : activeTab === 'auto' ? renderAutoTests() : activeTab === 'flagged' ? renderFlaggedTests() : activeTab === 'bugs' ? renderBugs() : renderConfig()}
          </div>
        </>
      )}

      {testToRun && (
        <TestRunner testCase={testToRun} onClose={() => setTestToRun(null)} onComplete={fetchData} />
      )}

      {showDeleteConfirm && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/45" onClick={() => setShowDeleteConfirm(false)}>
          <div className="bg-white rounded-2xl shadow-2xl p-5 max-w-[360px] w-[90%]" onClick={e => e.stopPropagation()}>
            <h3 className="text-sm font-bold text-surface-900 mb-1.5">Delete All Flagged Tests?</h3>
            <p className="text-[11px] text-surface-500 mb-3.5">This action cannot be undone. {flaggedList.length} test cases will be permanently deleted.</p>
            <div className="flex gap-1.5 justify-end">
              <button className="btn btn-gray" onClick={() => setShowDeleteConfirm(false)}>Cancel</button>
              <button className="btn" style={{background:'#b91c1c',color:'white'}} onClick={handleDeleteAllFlagged}>Delete All</button>
            </div>
          </div>
        </div>
      )}

      {showNewForm && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/45" onClick={() => { setShowNewForm(false); setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' }); }}>
          <div className="bg-white rounded-2xl shadow-2xl p-5 max-w-[420px] w-[90%]" onClick={e => e.stopPropagation()}>
            <h3 className="text-sm font-bold text-surface-900 mb-3.5">+ New Test Case</h3>
            <div className="flex flex-col gap-2.5">
              <div>
                <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Title *</label>
                <input className="finput w-full" value={newForm.title}
                  onChange={e => setNewForm({...newForm, title: e.target.value})} placeholder="Test case title" />
              </div>
              <div>
                <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Description</label>
                <textarea className="finput w-full resize-y min-h-[50px]" value={newForm.description}
                  onChange={e => setNewForm({...newForm, description: e.target.value})} placeholder="Optional description" />
              </div>
              <div className="flex gap-2.5">
                <div className="flex-1">
                  <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Type</label>
                  <Dropdown value={newForm.type} onChange={v => setNewForm({...newForm, type:v})}
                    options={['manual','integration','unit','e2e','security','performance'].map(t => ({value:t, label:t}))} style={{width:'100%'}} />
                </div>
                <div className="flex-1">
                  <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Priority</label>
                  <Dropdown value={newForm.priority} onChange={v => setNewForm({...newForm, priority:v})}
                    options={['low','medium','high','urgent','critical'].map(p => ({value:p, label:p}))} style={{width:'100%'}} />
                </div>
              </div>
            </div>
            <div className="flex gap-1.5 justify-end mt-3.5">
              <button className="btn btn-gray" onClick={() => { setShowNewForm(false); setNewForm({ title: '', description: '', type: 'manual', priority: 'medium' }); }}>Cancel</button>
              <button className="btn btn-green" onClick={handleNewTest}>+ Create</button>
            </div>
          </div>
        </div>
      )}

      {editTest && (
        <div className="fixed inset-0 z-[10000] flex items-center justify-center bg-black/45" onClick={() => setEditTest(null)}>
          <div className="bg-white rounded-2xl shadow-2xl p-5 max-w-[400px] w-[90%]" onClick={e => e.stopPropagation()}>
            <h3 className="text-sm font-bold text-surface-900 mb-1">Edit Test Case</h3>
            <p className="text-[11px] text-surface-500 mb-3.5">{editTest.testCaseId} — {editTest.title}</p>
            <div className="flex flex-col gap-2.5">
              <div>
                <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Status</label>
                <Dropdown value={editStatus} onChange={v => setEditStatus(v)}
                  options={ALL_STATUSES.map(s => ({value:s, label:s}))} style={{width:'100%'}} />
              </div>
              <div>
                <label className="text-[10px] font-medium text-surface-500 block mb-0.5">Assign to QA Tester</label>
                <Dropdown value={editAssignee} onChange={v => setEditAssignee(v)}
                  options={[{value:'', label:'Unassigned'}, ...qaMembers.map(m => ({value:m.user?._id, label:m.user?.name || m.user?.email}))]} style={{width:'100%'}} />
              </div>
            </div>
            <div className="flex gap-1.5 justify-end mt-3.5">
              <button className="btn btn-gray" onClick={() => setEditTest(null)}>Cancel</button>
              <button className="btn btn-blue" onClick={handleSaveEdit}>Save</button>
            </div>
          </div>
        </div>
      )}
    </div>
  );

  function renderAllTests() {
    if (testList.length === 0) {
      return (
        <div>
          <div className="flex items-center justify-between mb-2.5">
            <span className="text-xs font-semibold text-surface-900">All Test Cases (0)</span>
            <div className="flex gap-1.5">
              {canEdit && <button data-voice="new-test-case" className="btn btn-green text-[10px]" onClick={() => setShowNewForm(true)}>+ New Test Case</button>}
              {canEdit && <button data-voice="generate-tests" className="btn btn-blue text-[10px]" onClick={handleGenerateTests}>Generate from Tasks</button>}
              {canEdit && <button data-voice="generate-completed" className="btn btn-amber text-[10px]" onClick={handleGenerateCompleted}>From Completed Sprints</button>}
            </div>
          </div>
          <div className="text-center py-10 text-[11px] text-surface-400">No test cases yet.</div>
        </div>
      );
    }
    return (
      <div>
        <div className="flex items-center justify-between mb-2.5">
          <span className="text-xs font-semibold text-surface-900">All Test Cases ({testList.length})</span>
          <div className="flex gap-1.5">
            {canEdit && <button className="btn btn-green text-[10px]" onClick={() => setShowNewForm(true)}>+ New Test Case</button>}
            {canEdit && <button className="btn btn-blue text-[10px]" onClick={handleGenerateTests}>Generate from Tasks</button>}
            {canEdit && <button className="btn btn-amber text-[10px]" onClick={handleGenerateCompleted}>From Completed Sprints</button>}
          </div>
        </div>
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-5 gap-2.5">
          {TEST_COLUMNS.map(col => {
            const colTests = testList.filter(t => col.statuses.includes(t.status));
            return (
              <div key={col.key}
                onDragOver={e => { e.preventDefault(); e.currentTarget.classList.add('bg-primary-50/50'); }}
                onDragLeave={e => e.currentTarget.classList.remove('bg-primary-50/50')}
                onDrop={e => {
                  e.preventDefault();
                  e.currentTarget.classList.remove('bg-primary-50/50');
                  const testId = e.dataTransfer.getData('text/plain');
                  if (testId) handleTestDrop(testId, col.key);
                }}
                className="bg-surface-50/50 rounded-xl border border-surface-200 flex flex-col min-h-[200px]">
                <div className="flex items-center justify-between px-2.5 py-2 border-b border-surface-200">
                  <div className="flex items-center gap-1.5">
                    <div className="w-2 h-2 rounded-full" style={{ background: col.dot }} />
                    <span className="text-[11px] font-bold text-surface-700">{col.label}</span>
                  </div>
                  <span className="text-[9px] font-medium text-surface-400 bg-surface-100 px-1.5 py-0.5 rounded-full">{colTests.length}</span>
                </div>
                <div className="flex-1 p-1.5 space-y-1.5 min-h-[150px]">
                  {colTests.length === 0 ? (
                    <div className="text-center py-6 text-[9px] text-surface-300 italic">Drop tests here</div>
                  ) : colTests.map(tc => (
                    <div key={tc._id}
                      draggable
                      onDragStart={e => { e.dataTransfer.setData('text/plain', tc._id); setDraggedTest(tc._id); }}
                      onDragEnd={() => setDraggedTest(null)}
                      className={`bg-white rounded-lg border border-surface-200 border-t-2 ${
                        col.border
                      } p-2.5 cursor-grab hover:shadow-md hover:-translate-y-0.5 transition-all ${
                        draggedTest === tc._id ? 'opacity-50 shadow-lg' : ''
                      }`}>
                      <div className="flex items-start gap-1 mb-1">
                        <span className={`tbadge ${STATUS_CLASS[tc.status] || 'tb-todo'} text-[8px] leading-none`} style={{padding:'1px 5px'}}>{tc.status}</span>
                        {tc.autoGenerated && <span className="tbadge tb-todo text-[7px]" style={{padding:'1px 4px'}}>auto</span>}
                      </div>
                      <p className="text-[11px] font-semibold text-surface-900 leading-tight truncate">{tc.testCaseId} — {tc.title}</p>
                      <div className="flex items-center gap-1 mt-1 flex-wrap">
                        <span style={{fontSize:9,fontWeight:600,color:'#6b7280',background:'#f3f4f6',padding:'0 5px',borderRadius:4,lineHeight:'16px'}}>{tc.priority}</span>
                        <span style={{fontSize:9,color:'#9ca3af'}}>{tc.type}</span>
                        {tc.feature && <span style={{fontSize:9,color:'#9ca3af',maxWidth:80,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{tc.feature}</span>}
                      </div>
                      <div className="flex items-center justify-between mt-1.5 pt-1.5 border-t border-surface-100">
                        <span className="text-[9px] text-surface-500 font-medium truncate max-w-[70px]">{tc.assignee?.name || 'Unassigned'}</span>
                        <div className="flex gap-1">
                          {isManager && ['ready', 'in_progress', 'retesting'].includes(tc.status) && (
                            <button onClick={e => { e.stopPropagation(); setTestToRun(tc); }}
                              className="px-1.5 py-0.5 bg-blue-50 text-blue-700 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-blue-100 transition-colors leading-none">Run</button>
                          )}
                          {tc.status === 'in_progress' && isManager && (
                            <>
                              <button onClick={e => { e.stopPropagation(); handleInlineTestStatus(tc._id, 'passed'); }}
                                className="px-1.5 py-0.5 bg-emerald-50 text-emerald-700 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-emerald-100 transition-colors leading-none">Pass</button>
                              <button onClick={e => { e.stopPropagation(); handleInlineTestStatus(tc._id, 'failed'); }}
                                className="px-1.5 py-0.5 bg-red-50 text-red-700 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-red-100 transition-colors leading-none">Fail</button>
                              <button onClick={e => { e.stopPropagation(); handleInlineTestStatus(tc._id, 'blocked'); }}
                                className="px-1.5 py-0.5 bg-amber-50 text-amber-700 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-amber-100 transition-colors leading-none">Block</button>
                            </>
                          )}
                          {tc.status === 'failed' && (
                            <button onClick={e => { e.stopPropagation(); handleRetestTest(tc._id); }}
                              className="px-1.5 py-0.5 bg-amber-50 text-amber-700 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-amber-100 transition-colors leading-none">Retest</button>
                          )}
                          {canEdit && (
                            <button onClick={e => { e.stopPropagation(); handleOpenEdit(tc); }}
                              className="px-1.5 py-0.5 bg-surface-100 text-surface-600 rounded text-[8px] font-semibold border-none cursor-pointer hover:bg-surface-200 transition-colors leading-none">Edit</button>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            );
          })}
        </div>
      </div>
    );
  }

  function renderAutoTests() {
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>Auto-Generated Tests ({autoList.length})</div>
          <div style={{display:'flex',gap:6}}>
            {canEdit && <button data-voice="run-filter" className="btn btn-amber" onClick={handleRunFilter} style={{fontSize:10}}>🚩 Run Interest Filter</button>}
          </div>
        </div>
        {autoList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No auto-generated tests. Click "Generate from Tasks" to create.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {autoList.map(tc => (
              <div key={tc._id} className="task-row">
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className={`tbadge ${STATUS_CLASS[tc.status] || 'tb-todo'}`}>{tc.status}</span>
                    <span className="t-title" style={{fontSize:11}}>{tc.testCaseId} — {tc.title}</span>
                    <span className="tbadge" style={{
                      background: tc.interestMatchStatus === 'high' ? '#f0fdf4' : tc.interestMatchStatus === 'low' ? '#fffbeb' : '#fff1f2',
                      color: tc.interestMatchStatus === 'high' ? '#15803d' : tc.interestMatchStatus === 'low' ? '#b45309' : '#b91c1c',
                    }}>{tc.interestMatchScore}%</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    Match: {tc.interestMatchStatus} · Linked: {tc.linkedTask?.title || 'none'}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  {isManager && ['ready', 'in_progress'].includes(tc.status) && (
                    <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => setTestToRun(tc)}>▶ Run</button>
                  )}
                  {canEdit && (
                  <button className="btn btn-gray" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleOpenEdit(tc)}>Edit</button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderFlaggedTests() {
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>🚩 Flagged for Deletion ({flaggedList.length})</div>
          <div style={{display:'flex',gap:6}}>
            {flaggedList.length > 0 && (
              <>
                <button className="btn btn-green" style={{fontSize:10}} onClick={handleRestoreAll}>Restore All</button>
                {isAdmin && <button className="btn btn-red" style={{fontSize:10}} onClick={() => setShowDeleteConfirm(true)}>Delete All</button>}
              </>
            )}
          </div>
        </div>
        {flaggedList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No flagged test cases.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {flaggedList.map(tc => (
              <div key={tc._id} className="task-row" style={{borderLeft:'3px solid #ef4444'}}>
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className="tbadge tb-dl">{tc.interestMatchScore}% match</span>
                    <span className="t-title" style={{fontSize:11}}>{tc.testCaseId} — {tc.title}</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    Auto-delete: {tc.autoDeleteAt ? new Date(tc.autoDeleteAt).toLocaleDateString() : 'N/A'}
                    {tc.sprint && <> · Sprint: {tc.sprint.name}</>}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleRestoreFlagged(tc._id)}>↩ Restore</button>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderBugs() {
    return (
      <div>
        {bugStats && (
          <div className="stats-grid" style={{gridTemplateColumns:'repeat(6,1fr)',marginBottom:10}}>
            <div className="stat-pill"><div className="sp-n">{bugStats.total}</div><div className="sp-l">Total</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{bugStats.open}</div><div className="sp-l">Open</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b45309'}}>{bugStats.inProgress}</div><div className="sp-l">In Progress</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#15803d'}}>{bugStats.closed}</div><div className="sp-l">Closed</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#b91c1c'}}>{bugStats.critical}</div><div className="sp-l">Critical</div></div>
            <div className="stat-pill"><div className="sp-n" style={{color:'#c2410c'}}>{bugStats.reopened}</div><div className="sp-l">Reopened</div></div>
          </div>
        )}
        <div style={{fontSize:12,fontWeight:600,color:'#111827',marginBottom:8}}>Bugs ({bugList.length})</div>
        {bugList.length === 0 ? (
          <div style={{textAlign:'center',padding:'30px 0',color:'#9ca3af',fontSize:11}}>No bugs from test failures.</div>
        ) : (
          <div style={{border:'0.5px solid #e5e7eb',borderRadius:8,overflow:'hidden'}}>
            {bugList.map(bug => (
              <div key={bug._id} className="task-row">
                <div style={{flex:1,minWidth:0}}>
                  <div style={{display:'flex',alignItems:'center',gap:6}}>
                    <span className={`tbadge ${bug.status === 'open' ? 'tb-dl' : bug.status === 'in_progress' ? 'tb-ip' : bug.status === 'fixed' ? 'tb-rv' : bug.status === 'closed' ? 'tb-dn' : 'tb-dl'}`}>{bug.status}</span>
                    <span className={`tpriority ${SEVERITY_CLS[bug.severity] || 'tp-m'}`} style={{fontSize:10}}>{bug.severity}</span>
                    <span className="t-title" style={{fontSize:11}}>{bug.title}</span>
                  </div>
                  <div style={{fontSize:10,color:'#9ca3af',marginTop:2}}>
                    {bug.testCase?.testCaseId && <>From: {bug.testCase.testCaseId} · </>}
                    Assignee: {bug.assignee?.name || 'unassigned'}
                    {bug.retestCount > 0 && <> · Retests: {bug.retestCount}</>}
                  </div>
                </div>
                <div style={{display:'flex',gap:4,flexShrink:0}}>
                  {bug.status === 'open' && canEdit && (
                    <button className="btn btn-green" style={{fontSize:9,padding:'3px 8px'}} onClick={() => { const pid = bug.project?._id || bug.project; if (pid) navigate(`/projects/${pid}?tab=test-cases`); }}>✅ Resolve</button>
                  )}
                  {bug.status === 'closed' && isManager && (
                    <button className="btn btn-amber" style={{fontSize:9,padding:'3px 8px'}} onClick={() => handleReopenBug(bug._id)}>🔄 Reopen</button>
                  )}
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    );
  }

  function renderConfig() {
    const tagify = (val) => val.split(',').map(s => s.trim()).filter(Boolean);
    return (
      <div>
        <div style={{display:'flex',alignItems:'center',justifyContent:'space-between',marginBottom:10}}>
          <div style={{fontSize:12,fontWeight:600,color:'#111827'}}>⚙️ Interest Configuration</div>
          {canEdit && <button data-voice="save-config" className="btn btn-blue" style={{fontSize:10}} onClick={handleSaveInterestConfig}>💾 Save</button>}
        </div>
        <div style={{maxWidth:480,display:'flex',flexDirection:'column',gap:10}}>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Interest Tags</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.interestTags.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, interestTags: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. payment, auth, dashboard" />
          </div>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Priority Features</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.priorityFeatures.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, priorityFeatures: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. checkout, login, payment" />
          </div>
          <div>
            <label style={{fontSize:10,fontWeight:500,color:'#6b7280',display:'block',marginBottom:3}}>Ignore Patterns</label>
            <input className="finput" style={{width:'100%'}} value={interestConfig.ignorePatterns.join(', ')}
              onChange={e => setInterestConfig({...interestConfig, ignorePatterns: tagify(e.target.value)})}
              disabled={!canEdit} placeholder="e.g. legacy, deprecated, ui-only" />
          </div>
          <div style={{display:'flex',alignItems:'center',gap:12}}>
            <label style={{display:'flex',alignItems:'center',gap:6,fontSize:11,color:'#374151',cursor:'pointer'}}>
              <input type="checkbox" checked={interestConfig.autoDeleteEnabled}
                onChange={e => setInterestConfig({...interestConfig, autoDeleteEnabled: e.target.checked})}
                disabled={!canEdit} />
              Auto-delete enabled
            </label>
            {interestConfig.autoDeleteEnabled && (
              <div style={{display:'flex',alignItems:'center',gap:6}}>
                <span style={{fontSize:10,color:'#6b7280'}}>Delete after</span>
                <input type="number" min={1} max={30} value={interestConfig.autoDeleteDays}
                  onChange={e => setInterestConfig({...interestConfig, autoDeleteDays: parseInt(e.target.value) || 7})}
                  disabled={!canEdit}
                  style={{width:50,textAlign:'center',padding:'4px 6px',border:'0.5px solid #e5e7eb',borderRadius:5,fontSize:10,background:'#f9fafb',outline:'none'}} />
                <span style={{fontSize:10,color:'#9ca3af'}}>days</span>
              </div>
            )}
          </div>
          {canEdit && <button className="btn btn-amber" style={{fontSize:10,alignSelf:'flex-start'}} onClick={handleRunFilter}>🚩 Apply Interest Filter Now</button>}
        </div>
      </div>
    );
  }
}
